server:
  port: 8003
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Formation?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: root
    
  jpa:
    hibernate:
      ddl-auto: update